name: Deploy to staging

on:
  push:
    branches:
      - staging

jobs:
  deploy-staging:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          path: .

      - name: Generate robots.txt
        run: |
          cat > robots.txt <<EOL
          User-agent: *
          Disallow: /
          EOL

      - name: Change URL to staging location
        run: sed -i 's|https://www.rooters.it|https://r00ters.github.io|g' index.html 

      - name: Deploy site
        if: success() && env.GH_PAT != ''
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          repository-name: r00ters/r00ters.github.io
          branch: main
          folder: .
          git-config-name: ci-cd
          git-config-email: tech@rooters.it
          token: ${{ env.GH_PAT }}
          single-commit: true
          clean: true
          clean-exclude: |
            README*
            .git*
            sass
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
