name: Deploy to staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
         submodules: true
      - name: Generate robots.txt
        run: |
          cat > robots.txt <<EOL
          User-agent: *
          Disallow: /
          EOL
      - name: Deploy site
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          repo: https://github.com/r00ters/r00ters.github.io
          target_branch: gh-pages
          build_dir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
