name: Deploy to staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          path: .

      - name: Generate robots.txt
        run: |
          cat > static/robots.txt <<EOL
          User-agent: *
          Disallow: /
          EOL

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@4.10.2

      - name: Build
        run: STAGING=true gatsby build
      
      - name: Verify build
        run: ls -la public

      - name: Deploy site
        if: success() && env.GH_PAT != ''
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          repository-name: r00ters/r00ters.github.io
          branch: main
          folder: ./public/
          git-config-name: ci-cd
          git-config-email: tech@rooters.it
          token: ${{ env.GH_PAT }}
          single-commit: true
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GH_PAT}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
