name: Deploy to staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          path: .

      - name: Generate robots.txt
        run: |
          cat > src/robots.txt <<EOL
          User-agent: *
          Disallow: /
          EOL

      - name: Change URL to staging location
        run: sed -i 's|https://www.rooters.it|https://r00ters.github.io|g' src/index.html 

      - name: Deploy site
        if: success() && env.GH_PAT != ''
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          repository-name: r00ters/r00ters.github.io
          branch: main
          folder: ./src/
          git-config-name: ci-cd
          git-config-email: tech@rooters.it
          token: ${{ env.GH_PAT }}
          single-commit: true
          clean: true
          clean-exclude: |
            README*
            sass
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GH_PAT}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          channel: '#cicd'
          name: 'Rooters CI/CD Slack Bot'
          icon_emoji: ':poop:'
          icon_url: 'https://avatars.githubusercontent.com/u/78053076?s=200&v=4'