name: Deploy to staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          path: .

      - name: Generate robots.txt
        run: |
          cat > static/robots.txt <<EOL
          User-agent: *
          Disallow: /
          EOL

      - name: Deploy site
        if: success() && env.GH_PAT != ''
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-repo: r00ters/r00ters.github.io
          deploy-branch: main
          git-config-name: ci-cd
          git-config-email: tech@rooters.it
          token: ${{ env.GH_PAT }}
          single-commit: true
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GH_PAT}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
