name: Deploy to staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          path: build

      - name: Generate robots.txt
        run: |
          cat > build/robots.txt <<EOL
          User-agent: *
          Disallow: /
          EOL

      - name: Deploy site
        if: success() && env.GH_PAT != ''
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          repository-name: r00ters/r00ters.github.io
          branch: main
          folder: build
          token: ${{ env.GH_PAT }}
          single-commit: true
          clean: true
          clean-exclude: |
            README*
            .git*
            sass
        env:
          GH_PAT: ${{ secrets.GH_PAT }}