name: Deploy to staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: build

      - name: Generate robots.txt
        run: |
          cat > build/robots.txt <<EOL
          User-agent: *
          Disallow: /
          EOL

      - name: Deploy site
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          repo: r00ters/r00ters.github.io
          target_branch: main
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
