name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  deploy-production:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          path: .

      - name: Clean up
        run: |
          rm -rf README*
          rm -rf .git*
          rm -rf sass

      - name: Deploy site
        if: success() && env.AWS_ACCESS_KEY_ID != '' && env.AWS_SECRET_ACCESS_KEY != ''
        uses: siddolo/s3-deploy@master
        with:
          folder: .
          bucket: www.rooters.it
          bucket-region: eu-north-1
          private: true
          dist-id: E2AIKL71VMQ0PO
          invalidation: /
          delete-removed: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
