name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install project dependencies
        run: npm install

      - name: Build Next.js (static export)
        run: |
          npm run build

      - name: Verify static output
        run: ls -la out

      - name: Deploy site
        if: success() && env.AWS_ACCESS_KEY_ID != '' && env.AWS_SECRET_ACCESS_KEY != ''
        uses: siddolo/s3-deploy@hidden-files
        with:
          folder: ./out/
          bucket: www.rooters.it
          bucket-region: eu-north-1
          private: true
          dist-id: E2AIKL71VMQ0PO
          invalidation: /
          delete-removed: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  telegram-workflow-status:
    if: always()
    name: Post Workflow Status To Telegram
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          STATUS=${{ job.status }}
          MESSAGE="🚀 Workflow *${{ github.workflow }}* su *${{ github.repository }}* ha terminato con stato: *$STATUS* (job: ${{ github.job }})"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d parse_mode="Markdown" \
            -d text="$MESSAGE"
